backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  accept_roles: #optional - accepts all users if left out
      - admin
      - editor

# These lines should *not* be indented
media_folder: "static/assets" # Media files will be stored in the repo under static/assets
public_folder: "/assets" # The src attribute for uploaded media will begin with /assets
